match/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('match_app.urls')),
    path('', include('user_app.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

match_app/urls.py
from django.urls import path
from . import views

app_name = 'match_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:post_id>/', views.detail, name='detail'),
    path('add/', views.add, name='add'),
    path('edit/<int:post_id>/', views.edit, name='edit'),
    path('delete/<int:post_id>/', views.delete, name='delete'),
    path('contact/', views.contact, name='contact'),
    path('contact/done/', views.done, name='done'),
]

user_app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user_app'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='user_app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('user/<int:user_id>', views.detail, name='detail'),
    path('user/edit/<int:user_id>', views.edit, name='edit'),
    path('user/delete/<int:user_id>', views.delete, name='delete'),
]

match_app/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Tag(models.Model):
    tag = models.CharField('タグ名', max_length=50)
    def __str__(self):
        return self.tag

class Post(models.Model):
    title = models.CharField('タイトル', max_length=50)
    text = models.TextField('本文')
    image = models.ImageField('画像', upload_to = 'images', blank = True)
    created_at = models.DateTimeField('投稿日', default=timezone.now)
    tag = models.ForeignKey(Tag, verbose_name = 'タグ', on_delete = models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

user_app/models.py
from django.db import models

# Create your models here.

match_app/forms.py
from django import forms
from .models import Post, Tag
from django.forms import ModelForm

class PostAddForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'text', 'image', 'tag']

class ContactForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=50)
    email = forms.EmailField(label='メールアドレス',)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

user_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

match_app/views.py
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Tag
from .forms import PostAddForm, ContactForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.conf import settings
import textwrap
from django.core.mail import BadHeaderError, EmailMessage
from django.db.models import Q

def is_valid_q(q):
    return q != '' and q is not None

def index(request):
    posts = Post.objects.all().order_by('-created_at')
    title_or_user = request.GET.get('title_or_user')
    date_min = request.GET.get('date_min')
    date_max = request.GET.get('date_max')
    tag = request.GET.get('tag')

    if is_valid_q(title_or_user):
        posts = posts.filter(Q(title__icontains=title_or_user)
                        | Q(user__username__icontains=title_or_user)
                        ).distinct()

    if is_valid_q(date_min):
        posts = posts.filter(created_at__gte=date_min)

    if is_valid_q(date_max):
        posts = posts.filter(created_at__lt=date_max)

    if is_valid_q(tag) and tag != 'タグを選択...':
        posts = posts.filter(tag__tag=tag)

    return render(request, 'match_app/index.html', {'posts': posts, 'title_or_user': title_or_user , 'date_min': date_min, 'date_max': date_max ,'tag': tag})

def detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    return render(request, 'match_app/detail.html', {'post': post})

@login_required
def add(request):
    if request.method == "POST":
        form = PostAddForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('match_app:index')
    else:
            form = PostAddForm()
    return render(request, 'match_app/add.html', {'form': form})

@login_required
def edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = PostAddForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('match_app:detail', post_id=post.id)
    else:
        form = PostAddForm(instance=post)
    return render(request, 'match_app/edit.html', {'form': form, 'post':post })

@login_required
def delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    post.delete()
    return redirect('match_app:index')

def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        name = form.cleaned_data['name']
        message = form.cleaned_data['message']
        email = form.cleaned_data['email']
        subject = 'お問い合わせありがとうございます。'
        contact = textwrap.dedent('''
            ※このメールはシステムからの自動返信です。

            {name} 様
        
            お問い合わせありがとうございます。
            以下の内容でお問い合わせを受け付けました。
            内容を確認させていただき、ご返信させていただきますので、少々お待ちください。

            ----------------------------------

            ・お名前
            {name}

            ・メールアドレス
            {email}

            ・メッセージ
            {message}
            -----------------------------------
            
            作成者 shinya
        ''').format(
            name=name,
            email=email,
            message=message
        )
        to_list = [email]
        bcc_list = [settings.EMAIL_HOST_USER]
        try:
            message = EmailMessage(subject=subject, body=contact, to=to_list, bcc=bcc_list)
            message.send()
        except BadHeaderError:
            return HttpResponse('無効なヘッダが検出されました。')
        return redirect('match_app:done')

    return render(request, 'match_app/contact.html',{'form': form})


def done(request):
    return render(request, 'match_app/done.html')

user_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import SignUpForm
from django.contrib.auth import authenticate, login
from match_app .models import Post
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

def signup(request):
    signup_form = SignUpForm(request.POST or None)
    if request.method == "POST" and signup_form.is_valid():
        user = signup_form.save()
        input_username = signup_form.cleaned_data['username']
        input_email = signup_form.cleaned_data['email']
        input_password = signup_form.cleaned_data['password1']
        user = authenticate(username=input_username, email=input_email, password=input_password)
        login(request, user)
        return redirect('match_app:index')
    context = {
        "signup_form": signup_form,
    }
    return render(request, 'user_app/signup.html', context)

def detail(request, user_id):
    user = get_object_or_404(User, id=user_id)
    posts = user.post_set.all().order_by('-created_at')
    return render(request, 'user_app/detail.html', {'user': user, 'posts': posts})

@login_required
def edit(request, user_id):
    user = get_object_or_404(User, id=user_id)
    if request.method =="POST":
        form = SignUpForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('user_app:detail', user_id=user.id)
    else:
        form = SignUpForm(instance=user)
    return render(request, 'user_app/edit.html', {'form': form, 'user': user})

@login_required
def delete(request, user_id):
    user = get_object_or_404(User, id=user_id)
    user.delete()
    return redirect('match_app:index')

templates/base.html
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <meta name="description" content=""/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <title>Match</title>
  </head>
  <body>
    {% include 'header.html' %}
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  {% include 'footer.html' %}
  </body>
</html>

templates/footer.html
<footer>
 <h4 class="text-center">PortfolioSite</h4>
</footer>

templates/header.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'match_app:index' %}">PortfolioSite</a>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'match_app:index' %}">Home</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user_app:detail' request.user.id %}">My Page</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'match_app:add' %}">New Post</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user_app:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'user_app:signup' %}">Signup</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'user_app:login' %}">Login</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'match_app:contact' %}">Contact</a>
            </li>
        </ul>
    </div>
</nav>

templates/match_app/add.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<h1 class="mt-5 pt-4 text-center">New Post</h1>
<form action="{% url 'match_app:add' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <label for="id_title" class="sr-only">タイトル</label>
    <input type="text" name="title" placeholder="タイトル" maxlength="50" class="form-control mb-3" required id="id_title">

    <label for="id_text" class="sr-only">本文</label>
    <textarea type="text" name="text" placeholder="本文" cols="40" rows="10" class="form-control mb-3" required id="id_text"></textarea>

    <div class="mb-3 form-control text-secondary">
        <label>画像</label>
            {{ form.image }}
    </div>
    
    <div class="mb-3">
        <label for="id_tag" class="sr-only">タグ</label>
            {{ form.tag|add_class:"custom-select" }}
    </div>

    <button type="submit" class="btn btn-block btn-outline-success">Post</button>
</form>
{% endblock %}

templates/match_app/contact.html
{% extends 'base.html' %}
{% block content %}   

<div class="container">
<h1 class="mt-5 pt-4 text-center">Contact</h1>
<form action="{% url 'match_app:contact' %}" method="POST">
 {% csrf_token %}
 <label for="id_name" class="sr-only">お名前</label>
 <input class="form-control mb-3" name="name" maxlength="50" required="" id="id_name" type="text" placeholder="お名前">

 <label for="id_email" class="sr-only">メールアドレス</label>
 <input type="email" name="email" required="" id="id_email" placeholder="メールアドレス" class="form-control mb-3">

 <label for="id_message" class="sr-only">メッセージ:</label>
 <textarea name="message" cols="40" rows="10" required="" id="id_message" placeholder="メッセージ" class="form-control mb-3"></textarea>

<button type="submit" class="btn btn-block btn-outline-success">Send</button>
</form>
</div>
{% endblock %}

templates/match_app/detail.html
{% extends 'base.html' %}
{% block content %} 

<div class="card text-secondary" style="margin-top: 55px;">
  {% if post.image %}
  <img style="width: 100%; max-height: 500;" class="img-fluid mx-auto" src="{{ post.image.url }}">
  {% else %}
  <div class="p-1 border border-secondary text-center pt-5" style="min-width: 500; min-height: 400;">No Image</div>
  {% endif %}  <div class="card-body">
    <h3 class="card-title font-weight-bold text-center">{{ post.title }}</h3>
    <div class="p-3">
    <p class="card-text">{{ post.text }}</p>
    <p>#{{post.tag}}</p>
    <p>{{post.created_at}}</p>
    {% if request.user == post.user %}
    <a href="{% url 'match_app:edit' post_id=post.id %}"><button type="button" class="btn btn-outline-primary"> Edit </button></a>
    <a href="{% url 'match_app:delete' post_id=post.id %}"><button type="button" class="btn btn-outline-danger">Delete</button></a>
    {% endif %}
  </div>
</div>
</div>
{% endblock %}

templates/match_app/done.html
{% bootstrap_css %} 
{% bootstrap_javascript jquery='full' %}
<div class="m-5 text-center">
<div class="card d-inline-block">
 <div class="card-body p-4">
   <h4 class="card-title">お問い合わせありがとうございます。</h4>
  <hr>
   <a href="{% url 'match_app:index' %}"><button type="button" class="btn btn-primary">トップページへ</button></a>
 </div>
</div>
</div>

templates/match_app/edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<h1 class="mt-5 pt-4 text-center">編集</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <label for="id_title" class="sr-only">タイトル</label>
    {{ form.title|add_class:"form-control mb-3"}}
    <label for="id_text" class="sr-only">本文</label>
    {{ form.text|add_class:"form-control mb-3"}}

    <div class="mb-3 form-control text-secondary">
    <label>画像</label>
        {{ form.image }}
    </div>

    <div class="my-5">
    <label for="id_tag" class="sr-only">タグ</label>
    {{ form.tag|add_class:"custom-select" }}
    </div>

    <button type="submit" class="btn btn-block btn-outline-success">編集する</button>
</form>

{% endblock %}

templates/match_app/filter.html
<h4 class="card-title text-secondary text-center">絞り込み検索</h4>
<form method="GET" action="{% url 'match_app:index' %}">
 <div class="form-row">
     <div class="form-group col-12">
         <div class="input-group">
             <input class="form-control py-2 border-right-0 border" type="search" name="title_or_user" placeholder="タイトル or ユーザー名..." value="{{request.GET.title_or_user}}" />
             <span class="input-group-append">
                 <div class="input-group-text bg-transparent">
                     <i class="fa fa-search"></i>
                 </div>
             </span>
         </div>
     </div>        
 </div>
 <div class="form-row">
   <div class="form-group col-md-12 col-lg-6">
     <label for="publishDateMin">開始日〜</label>
     <input type="date" class="form-control" id="publishDateMin" name="date_min" value="{{request.GET.date_min}}">
   </div>
   <div class="form-group col-md-12 col-lg-6">
     <label for="publishDateMax">〜終了日</label>
     <input type="date" class="form-control" id="publishDateMax" name="date_max" value="{{request.GET.date_max}}">
   </div>
   <div class="form-group col-md-12">
     <label for="category">タグ</label>
     <select id="tag" class="form-control" name="tag">
       <option selected>タグを選択...</option>
       {% for tag in tags %}
       <option value="{{ tag }}">{{ tag }}</option>
       {% endfor %}
     </select>
   </div>
 </div>
 <button style="width: 100%;" type="submit" class="btn btn-primary">絞り込み</button>
</form>

templates/match_app/index.html
{% extends 'base.html' %}
{% block content %}
<h1 class="mt-5 pt-4 text-center">PortfolioSite</h1>

<button data-toggle="modal" data-target=".bd-example-modal-lg" style="margin: 0 auto;" type="button" class="btn btn-primary d-block my-3 px-5"><i class="fa fa-search">Search</i></button>
  <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-xl">
      <div class="modal-content">
        <div class="card text-align-center">
          <div class="card-body">
            {% include 'match_app/filter.html' %}
          </div>
        </div>
      </div>
    </div>
  </div>
{% if title_or_user or date_min or date_max or tag %}
<p class="mb-0 text-center font-weight-bold h3">検索結果：{{posts.count}}件</p>
<table class="table table-bordered">
  <thead class="thead-light">
    <tr>
      <th>タイトル or ユーザー名</th>
      <th>開始日〜終了日</th>
      <th>タグを選択</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{request.GET.title_or_user}}</td>
      <td>{{request.GET.date_min}}〜{{request.GET.date_max}}</td>
      <td>{{request.GET.tag}}</td>
    </tr>
  </tbody>
</table>
{% endif %}

<div class="d-flex justify-content-center flex-wrap">
{% for post in posts%}
<a href="{% url 'match_app:detail' post_id=post.id %}">
  <div class="card m-4" style="min-width: 300; max-height: 490;">
    {% if post.image %}
    <img style="max-width: 300; max-height: 300;" class="card-img-top" src="{{ post.image.url }}">
    {% else %}
    <div class="p-1 border border-secondary text-center pt-5" style="min-width: 300; min-height: 225;">No Image</div>
    {% endif %}
    <div class="card-body">
      <h4 class="card-title">{{post.title|truncatechars:10 | linebreaksbr}}</h4>
      <p class="card-text">
        {{ post.text|truncatechars:17 }}
      </p>
    </a>
      <p>#{{post.tag}}</p>
      <p>{{post.created_at}} |
      <a href="{% url 'user_app:detail' post.user.id %}">{{post.user.username}}</a></p>
  </div>
</div>
{% endfor %}
</div>
{% endblock %}

templates/user_app/detail.html
{% extends 'base.html' %}
{% block content %}   
<h1 class="text-center my-5">{{ user.username }}'s Page</h1>

{% if request.user == user %}
<div class="text-center"><a href="{% url 'user_app:edit' user_id=user.id %}"><button type="button" class="btn btn-outline-info">Edit {{user}}</button></a></div>
{% endif %}

<div class="d-flex justify-content-center flex-wrap">
    {% for post in posts%}
    <a href="{% url 'match_app:detail' post_id=post.id %}">
        <div class="card m-4" style="min-width: 300; max-height: 490;">
        {% if post.image %}
        <img style="max-width: 300; max-height: 300;" class="card-img-top" src="{{ post.image.url }}">
        {% else %}
        <div class="p-1 border border-secondary text-center pt-5" style="min-width: 300; min-height: 225;">No Image</div>
        {% endif %}
        <div class="card-body">
            <h4 class="card-title">{{post.title|truncatechars:10 | linebreaksbr}}</h4>
            <p class="card-text">
                {{ post.text|truncatechars:17 }}
            </p>
        </a>
            <p>#{{post.tag}}</p>
            <p>{{post.created_at}}</p>

        </div>
    </div>
    {% endfor %}
    </div>
{% endblock %}

templates/user_app/edit.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<h1 class="mt-5 pt-4 text-center">Edit {{user.username}}</h1>
    <form class="form-signin" method="post">
        {% csrf_token %}

        <label for="id_username" class="text-secondary">名前</label>
        {{ form.username|add_class:"form-control mb-3" }}

        <label for="id_email" class="text-secondary">メールアドレス</label>
        {{ form.email|add_class:"form-control mb-3"}}

        <label for="id_password1" class="text-secondary">新しいパスワード</label>
        {{ form.password1|add_class:"form-control mb-3"}}

        <label for="id_password2" class="text-secondary">パスワード(確認用)</label>
        {{ form.password2|add_class:"form-control mb-3"}}

        <button type="submit" class="btn btn-block btn-outline-success">Edit</button>
    </form>

    {% if request.user == user %}
    <a href="{% url 'user_app:delete' user_id=user.id %}"><button type="button" class="btn btn-outline-danger">Delete</button></a>
    {% endif %}

{% endblock %}

templates/user_app/login.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<h1 class="mt-5 pt-4 text-center">Login</h1>
<form method="post">
{% csrf_token %}
<label for="id_username" class="sr-only">ユーザー名</label>
<input type="text" name="username" placeholder="ユーザー名" autofocus autocapitalize="none" autocomplete="username" maxlength="150" class="form-control mb-3" required id="id_username">

<label for="id_password" class="sr-only">パスワード</label>
<input type="password" name="password" autocomplete="current-password" placeholder="パスワード" class="form-control mb-3" required id="id_password">

<button type="submit" class="btn btn-block btn-outline-success">Login</button>
</form>
<p>アカウントをお持ちでない方→ <a href="{% url 'user_app:signup' %}">Signup</a></p>
{% endblock %}

templates/user_app/signup.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
<h1 class="mt-5 pt-4 text-center">Signup</h1>
    <form class="form-signin" method="post">
        {% csrf_token %}
        <label for="id_username" class="sr-only">ユーザー名</label>
        <input type="text" name="username" placeholder="名前" maxlength="150" class="form-control mb-3" required id="id_username" autofocus>

        <label for="id_email" class="sr-only">メールアドレス</label>
        <input type="email" name="email" placeholder="メールアドレス" maxlength="254" class="form-control mb-3" required id="id_email">

        <label for="id_password1" class="sr-only">パスワード</label>
        <input type="password" name="password1" placeholder="パスワード*" autocomplete="new-password" class="form-control mb-3" id="id_password1">

        <label for="id_password2" class="sr-only">パスワード(確認用)</label>
        <input type="password" name="password2" placeholder="パスワード(確認用)*" autocomplete="new-password" class="form-control mb-3" required id="id_password2">

        <button type="submit" class="btn btn-block btn-outline-success">Signup</button>
    </form>
        <p>既にアカウントをお持ちの方→ <a href="{% url 'user_app:login' %}">Login</a></p>
        <p>* ８文字以上</p>
</div>
</div>
{% endblock %}